# Generated by Django 5.1.7 on 2025-03-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_color',
            field=models.CharField(default='#000000', help_text='hexadecimal color code (e.g., #000000)', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='font_color',
            field=models.CharField(default='#ffffff', help_text='hexdecimal color code (e.g., #ffffff)', max_length=7),
        ),
        migrations.AddField(
            model_name='upcomingproject',
            name='background_color',
            field=models.CharField(default='#000000', help_text='hexadecimal color code (e.g., #000000)', max_length=7),
        ),
        migrations.AddField(
            model_name='upcomingproject',
            name='font_color',
            field=models.CharField(default='#ffffff', help_text='hexdecimal color code (e.g., #ffffff)', max_length=7),
        ),
    ]
