# Generated by Django 5.1.7 on 2025-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contentblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='video_url',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/'),
        ),
    ]
