# Generated by Django 5.1.7 on 2025-03-25 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_contentblock_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='object_id',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='core.project'),
        ),
    ]
