# Generated by Django 5.1.7 on 2025-04-06 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_contentblock_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='object_id',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='content_blocks/images/'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='core.project'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='upcoming_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='core.upcomingproject'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
