# Generated by Django 5.1.7 on 2025-04-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='the main text contetn of the service page')),
                ('image', models.ImageField(blank=True, help_text='An optional image for the service page', null=True, upload_to='services_images/')),
            ],
        ),
    ]
