# Generated by Django 5.1.7 on 2025-04-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servicecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the person contacting', max_length=200)),
                ('email', models.EmailField(help_text='the email address of the person contacting', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='optionaal phone number', max_length=15, null=True)),
                ('message', models.TextField(help_text='The mesage submitted by the user')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=' Timestamp for when the contact submit their info')),
            ],
        ),
    ]
