# Generated by Django 5.1.7 on 2025-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display text for the link (eg. Facebook)', max_length=100)),
                ('url', models.CharField(help_text=" The URL of the social  media profile (e.g., 'https://facebook.com/example')", max_length=500)),
            ],
        ),
    ]
